
services:
  app:
    # Root-level Dockerfile builds: 1) React bundle, 2) Python backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI exposed port

    environment:
      PYTHONUNBUFFERED: "1"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
