
services:
  app:
    # Root-level Dockerfile builds: 1) React bundle, 2) Python backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI exposed port

    # Load all variables from local .env (OPENAI_API_KEY, PROAPIS_KEY, etc.)
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      # Allow explicit override via docker-compose CLI if desired
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      PROAPIS_KEY: "${PROAPIS_KEY}"
      LANGSMITH_API_KEY: "${LANGSMITH_API_KEY}"
      LANGSMITH_TRACING: "${LANGSMITH_TRACING}"
